### ISSUE TITLE
Add flag to `Please make changes to my PR`

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#163]
Right now if someone wants to contribute they do a PR, we review and give feedback, and then we iterate this process a couple of times until the PR is done. With @rabitt we're thinking of adding a flag `Please make changes to my PR [PMC]` or similar to speed up closing PRs after a couple of iterations. That flag will indicate that someone else can jump in the code an make the last changes to merge it. Thoughts?

**Comment by lostanlen** [comment]
i'm not sure what the use case is for this. how do you incentivize contributors to do this?

**Comment by lostanlen** [comment]
reading this again, it seems like there is already an issue tag which kind of addresses this: `help wanted. JuliaLang has `up for grabs`, which might work too. But I'm totally OK with creating a `PMC` tag. It's just that the acronym is not obvious.

**Comment by lostanlen** [comment]
@magdalenafuentes do you want to go with `help wanted` (already provided by GitHub) or make a custom `PMC` tag?

**Comment by rabitt** [comment]
When me and @magdalenafuentes discussed this initially, our thought was the "please make changes" option would be "on" by default, in order to reduce the friction for contributing. To this extent, maybe instead of "please make changes" as a tag we can have a "please do not make changes" tag, which would be there for people who want to start and finish the PR themselves. What do you think?

**Comment by rabitt** [comment]
Closed with new label "please-do-not-edit"
