### ISSUE TITLE
tempo vs bpm

### ISSUE THREAD

**Issue by lostanlen** [mir-dataset-loaders/mirdata#221]
The recently added loader Groove MIDI has a `bpm` field. (after #207) 
In contrast, GuitarSet and RWC Popular datasets have a `tempo` field.
Perhaps it's worth unifying the two property names? (ties down with #176)

**Comment by rabitt** [comment]
This opens up a bit of a can of worms - we already don't have consistency across datasets for many things. For example, orchest has `audio_stereo` and `audio_mono`, and no `audio`, the tempo inconsistencies you mention, and I'm sure we can find examples of others.

Kicking the can down the road for #176, I prefer to keep the names of attributes to be consistent with the dataset itself, rather than trying to make everything conform to a standard. That said, in this case, `bpm` vs `tempo` is not a big change, so I'm don't mind updating this one, since `tempo` is perhaps more descriptive than `bpm`
