### ISSUE TITLE
`module.load_*` should raise `IOError`, not return `None`

### ISSUE THREAD

**Issue by lostanlen** [mir-dataset-loaders/mirdata#222]
raised by @rabitt in a meeting today

Many of the module-specific loaders, e.g. `orchset.load_melody`, return `None` if the argument does not exist. This can be confusing in the sense that it may suggest that the file exists but that there is no annotation for this file, or that the annotation is not applicable (non-melodic music, following my example above).

She now recommends raising an `IOError`. 

This is a breaking change so i wouldn't recommend it for v0.2
But we can deprecate it in v0.2 and change the behavior in v0.3

@rabitt what should we do for people providing new loaders? Should we tell them to work with the old or the new convention? 
This affects `new_loader.md` (excerpt below):

```
# -- Write any necessary loader functions for loading the dataset's data
def load_annotation(annotation_path):
    if not os.path.exists(annotation_path):
        return None
```

**Comment by rabitt** [comment]
@lostanlen this is a variant of #196

**Comment by rabitt** [comment]
Note that - I'd suggest the following behavior:
1. If the input to load_* is `None`, return `None` (this is for datasets where some annotations are not available)
2. If the input is a path which does not exist, raise an `IOError`

**Comment by lostanlen** [comment]
> If the input to load_* is None, return None (this is for datasets where some annotations are not available)

@rabitt does this really need to happen at the track level, though? couldn't we write a utility function which filters the index based on a given annotation type?

```
melody_index = {
    track_id: mirdata.orchset.DATA.index[track_id]
    for track_id in mirdata.orchset.DATA.index
    if "melody" in mirdata.orchset.DATA.index[track_id]
}
```

guaranteed without `KeyError`

**Comment by lostanlen** [comment]
@rabitt to be clear, you think that `load_metadata` should also `IOError` if metadata hasn't been downloaded yet? This implies that we won't be able to construct most `Track` objects from a bare filesystem environment.

**Comment by lostanlen** [comment]
(this is exactly why i think that we should pass `(index[track_id], metadata[track_id])`, not `track_id`, to the `Track` constructor. In this way, the `load` function can check ahead of time whether `metadata` is available in the filesystem or not. If not, it could replace it by `None` on the fly iff `track_id` belongs to `index`, and return a `KeyError` if the `track_id` doesn't belong to `index`. This allows to make a clear distinction between "this track ID belongs to the dataset, but we don't have metadata for it" vs "this track ID does not belong to the dataset")

**Comment by lostanlen** [comment]
The spiel above was for metadata.

For properties (`beats`, `sections`, etc.), i'm realizing that we can work out an elegant solution by modulating `utils.cached_property.__get__` to our liking. By default, `orchset.Track(track_id).melody` would
-> raise an `AttributeError` if the property is not implemented
-> raise a `KeyError` if the property is implemented but the file is not present in the index
-> raise a `FileNotFoundError` if the property is implemented, the file is present in the index, but the file is not present in the filesystem
-> raise a `ChecksumError` if the property is implemented, the file is present in the index, but it has an invalid checksum
-> raise an `IOError` if the property is implemented, the file is present in the index, it has a valid checksum, but the `module.load_*` function failed
-> return+cache the immutable value from `module.load_*` if all of the above was successful. Now, this value is `None` if _and only if_ the `module.load_*` is `None`. 

I think that doing this would simplify troubleshooting tremendously. The backtraces would be much easier to understand.

The only change for this to work is to ensure that there's a consistent match between index keys and property names. The only index which doesn't satisfy this rule is `beatles`. I can volunteer for that.

**Comment by rabitt** [comment]
I think two things are being conflated here - can we keep this discussion to "what should the `dataset.load_*` functions do, and keep the "how should the `Track` class behave" to #224 ? Otherwise it's very hard to keep the discussions focused :)

`dataset.load_*` does _not_ live at the track level right now - but instead at the module level. These functions are called by the `Track` objects, for example, `dataset.Track.beats` internally calls `dataset.load_beats`.

Wanted to clear that up first - responding to your other points below.

**Comment by rabitt** [comment]
> @rabitt to be clear, you think that load_metadata should also IOError if metadata hasn't been downloaded yet? This implies that we won't be able to construct most Track objects from a bare filesystem environment. (i.e. we'll have to do download before load, never the other way around)

`dataset._load_metadata()` is a tricky case and we should think about it separately from `dataset.load_*` (I wasn't thinking about metadata in this issue at all actually)... We're returning None when the file doesn't exist to support #188 - if you're using mirdata on a computer different from where the datasets live, it's unusable if the metadata is forced to be on the same computer, but there are still parts of the api that work fine without metadata (e.g. paths to audio files and anntoations). That's why we historically decided to return None when the metadata doesn't exist.

**Comment by rabitt** [comment]
> For context: this is exactly why i think that we should pass (index[track_id], metadata[track_id]), not track_id, to the Track constructor.

@lostanlen can you move this whole disucssion to #224 ?

**Comment by rabitt** [comment]
> For properties (beats, sections, etc.), i'm realizing that we can work out an elegant solution by modulating utils.cached_property.__get__ to our liking. By default, orchset.Track(track_id).melody would
(1) raise an AttributeError if the property is not implemented
(2) raise a KeyError if the property is implemented but the file is not present in the index
(3) raise a FileNotFoundError if the property is implemented, the file is present in the index, but the file is not present in the filesystem
(4) raise a ChecksumError if the property is implemented, the file is present in the index, but it has an invalid checksum
(5) raise an IOError if the property is implemented, the file is present in the index, it has a valid checksum, but the module.load_* function failed
(6) return+cache the immutable value from module.load_* if all of the above was successful. Now, this value is None if and only if the corresponding module.load_* is None (i.e. a rare case where human annotators have deliberately chosen to annotate the track as None)
>
>Cases (1-4) are in mirdata.utils code. Case (5) is in csv parsing code. Case (6) is in module-specific code.

In order to support #188 , we separated the `dataset.load_*` functions from the Track object, which calls them for the relevant filepaths. `dataset.load_*` can take any filepath, independently of any track index, and it's in these functions i'd like to raise an IOError when a file does not exist. 

Aside from this - it sounds like this whole discussion above is proposing moving these attributes to the `track.Track` attribute. For that, let's move the discussion to #224 . Let's talk about `dataset.load_*` behavior as a standalone function, knowing that the Track objects call these directly.

**Comment by rabitt** [comment]
> > If the input to load_* is None, return None (this is for datasets where some annotations are not available)
> 
> @rabitt does this really need to happen at the track level, though? couldn't we write a utility function which filters the index based on a given annotation type?
> 
> ```
> melody_index = {
>     track_id: mirdata.orchset.DATA.index[track_id]
>     for track_id in mirdata.orchset.DATA.index
>     if "melody" in mirdata.orchset.DATA.index[track_id]
> }
> ```
> 
> guaranteed without `KeyError`

So again - this is maybe a misunderstanding - none of this behavior happens explicitly at the Track level, but in standalone, module-level functions. 

On this:
> > If the input to load_* is None, return None (this is for datasets where some annotations are not available)

This is only necessary for some datasets (e.g. salami) where there are missing annotations for some tracks. Otherwise, most loaders won't need this behavior anyway. So in the vast majority of dataset modules, we could have, e.g. 
`dataset.load_beats(filepath)` return `BeatData` when `filepath` exists, and raise an `IOError` when it does not.
