### ISSUE TITLE
docs audit

### ISSUE THREAD

**Issue by rabitt** [mir-dataset-loaders/mirdata#245]
We should do an audit of our [docs](https://mirdata.readthedocs.io/en/latest/index.html) before releasing 0.3.0 - we have some (small but visible) formatting issues and some outstanding TODO's. 

+ tie the docs version to the mirdata version

**Comment by magdalenafuentes** [comment]
on doc issues:

- inconsistency of docs format: some loaders use numpy docs style, other use some other format

**Comment by magdalenafuentes** [comment]
All in one place looking at release 0.3:

- [ ] Tie the docs version to the mirdata version
- [ ] Add diagram explaining how mirdata works
- [ ] Stand mirdata design principles
- [ ] Taxonomy / ontology with data types
- [ ] Inconsistency of docs format: some loaders use numpy docs style, other use some other format
- [ ] Inconsistency on " and ' because of black formatting

**Comment by rabitt** [comment]
@PRamoneda @genisplaja @nkundiushuti You mentioned that you found some problems with the documentation when you were first looking at mirdata. If you have ideas for things we can add to make things easier to understand, or some examples of things that were confusing let us know!

**Comment by nkundiushuti** [comment]
We had a few suggestions. Maybe the info is already there in contributing but it's not very clear 

> Design a simple loader, without the need to add extra functionality to mirdata
> Write docstrings to _each new function_ you add 
> Write tests for _every_ function you add 
> Run the 3 test lines mentioned in the contributing to make sure everything is ok
> Rebase with the latest changes from master and fix conflicts 
> Run black only at the end (before the last commit and after running all tests), solely on the files you have changed, and using --skip-string-normalization

**Comment by genisplaja** [comment]
I agree with the points listed by @nkundiushuti! From what he stated, I think the most important point is to remark that every function has to be tested! 
I would remind the contributors that a `raise IOError()` has to be present in every method that loads files. In addition, I think it could be useful to write down that the annotations that stay the same during the whole track (for instance, Mridangam's tonic or stroke name) should be introduced to JAMS metadata, and also that methods to load annotations that do not load files should be avoided.

**Comment by PRamoneda** [comment]
I would add some info about `Data types` or even about `to_jams` function... Most of our problems are around those two topics.

**Comment by magdalenafuentes** [comment]
Moving conversation from #284 here. Will be partially addressed by #336 but also needs to be properly integrated in Docs and CONTRIBUTING:

1. We should explain how we use data types because it's not obvious (e.g. list of BeatData vs. BeatData containing arrays of beat times and positions).
2. We should clarify that we follow mir_eval conventions, for contributors adding new data types.
3. Convention is: if annotation doesn't change over time is part of metadata (e.g. genre->str) and if it does change thenb it becomes a data type

**Comment by magdalenafuentes** [comment]
Part of this was already done in #370 #368 #363 and #367.

Remaining: Tutorials

**Comment by genisplaja** [comment]
Ok!! "Getting started" part is missing as well (as stated in #358)?

**Comment by magdalenafuentes** [comment]
`Getting Started` became a header to group `overview`, `Supported datasets and annotations` and `tutorials`, so I think is only `Tutorials` what's left

**Comment by magdalenafuentes** [comment]
I'm gonna close this one to focus on #364. However, @PRamoneda and @genisplaja feel free to comment/fix anything you might see in the docs! we tried to go over most things we discussed but we might have missed something!
