### ISSUE TITLE
ASMD library

### ISSUE THREAD

**Issue by PRamoneda** [mir-dataset-loaders/mirdata#299]
In the last SMC Torino 2020 conference was presented this "dataset loaders library":
https://framagit.org/sapo/asmd/
Here the docs!
https://asmd.readthedocs.io

- Currently It only has one dataset
- It is focused on datasets with audio and score at the same time.

**Comment by rabitt** [comment]
I'm not clear why they decided to make a new library instead of working with us - the reason they give in [the paper](https://arxiv.org/pdf/2003.01958.pdf) is:

> A similar effort is held by mirdata [11], a Python package for downloading and using common MIR datasets.  However, our work is more focused on multimodality and tries to keep the entire framework easily extensible and modular.

We do support audio + score, and we are doing our best to make the framework easily extensible & modular :). Of course things can always be improved.

For now, I'd say if they want to talk with us they can!

**Comment by PRamoneda** [comment]
Then close
