### ISSUE TITLE
Dataset object download_info and readme

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#400]
Looking at #300 I realized that many dataset loaders don't have the `readme` implemented (I checked a few), but it appears in the [docs of the `Dataset` object](https://mirdata.readthedocs.io/en/latest/source/mirdata.html#module-mirdata.initialize). Should we implement it or update the docs?

Also, in the docs it appears that `download_info` is visible, but it currently isn't `_download_info`. We should make it visible right @rabitt ?

**Comment by rabitt** [comment]
On the readme - this is the one thing I removed when updated to the new new API. I didn't find an easy way to load the docstring from the module itself from within the module. I wasn't too upset to remove it though - for me, its why the documentaiton exists! But if you want to still have something in the code, maybe we can have a Dataset object defined .readme for all Datasets which prints a link to the readthedocs page. 

On download_info - good catch! It's in the documentation for the Dataset object (by mistake). I'd removed it from being since it's meant to be part of the download function. I was afraid of confusing people when download_info is None, making them thinking there's nothing to download - but in fact those are the most perfectly downloadable datasets! Either way we need to fix the inconsistency!

**Comment by magdalenafuentes** [comment]
I like the `dataset.readme` printing a link to the docs or something like that, but I'm ok either way! @nkundiushuti thoughts?

Also ok either way with the download_info. It might be slightly better to be hidden.

**Comment by rabitt** [comment]
This is fixed in #410
