### ISSUE TITLE
Test track Assertion Error in "Beatport_Key", "Giantsteps_Key" and "Mtg_jamando_autotagging" test files!!

### ISSUE THREAD

**Issue by prachitui** [mir-dataset-loaders/mirdata#520]
Hello, I tried cloning the repository and every time I run the "pytest tests/ --local" it gives me the error below
**FAILED tests/datasets/test_beatport_key.py::test_track - AssertionError: audio shape (89856,) was not (88200,)
FAILED tests/datasets/test_giantsteps_key.py::test_track - AssertionError: audio shape (89856,) was not (88200,)
FAILED tests/datasets/test_mtg_jamendo_autotagging_moodtheme.py::test_track - AssertionError: audio shape (2, 89856) was not (2, 88200)**

The same error occurred in test track of salami dataset as well but I fixed it by downloading ffmpeg. I don't know why these tests are not passing. Please Help.

**Comment by prachitui** [comment]
@magdalenafuentes @rabitt @genisplaja @nkundiushuti @PRamoneda

**Comment by genisplaja** [comment]
Hello @prachitui, thanks for bringing this up! This may be due to the different encoding systems of the .mp3 files and your environment. One suggestion is that you ignore this issue. You should be able to use and contribute to mirdata as long as all the tests pass when you create a pull request in the repository. However, you can also check your audio encoding module versions: ffmpeg/audioread/soundfile.

**Comment by prachitui** [comment]
> Hello @prachitui, thanks for bringing this up! This may be due to the different encoding systems of the .mp3 files and your environment. One suggestion is that you ignore this issue. You should be able to use and contribute to mirdata as long as all the tests pass when you create a pull request in the repository. However, you can also check your audio encoding module versions: ffmpeg/audioread/soundfile.

@genisplaja Yes, I have made all the files and I am going to create a pull request that's why I was worried about the issue. I'll drop a comment here if I come across any issue.
