### ISSUE TITLE
RWC beat parsing 

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#79]
The actual parsing of beat positions in the RWC collections is probably wrong, trying to get information to get it right.

**Comment by magdalenafuentes** [comment]
Changed the parsing, now it's working, but found problems in the annotations in a few files.

I found files with two consecutive beats labeled as downbeats:
- RM-C007
- RM-C012
- RM-C019
- RM-C025
- RM-C035
- RM-G062
- RM-G083

and a file with several contiguous beats annotated with the same label (here label=position inside bar):
- RM-G079

I'm not sure what to do here, since making modifications means editing the annotations. I guess the options are:

1. Listen the examples and decide what to do with the double downbeats
2. Propagate the annotations ignoring the equally-labeled beats in RM-G079
3. Do nothing and respect the annotations as they are

Opinion? @rabitt @lostanlen

**Comment by rabitt** [comment]
I guess this is a more tricky philosophical question - what do we want to do when we find "obvious" mistakes in annotations? On the one hand, if it's clear how it should be fixed, and most people are probably fixing it in their code already, it might make sense to fix it. On the other hand, it's a dangerous path to start correcting things ourselves... we don't want to start creating diverging versions of datasets where there's a 'mirdata version' and the 'original version'. 

My opinion is, until we decide otherwise, to respect the annotations as they are even if we know there are mistakes. Maybe we can create a place in the documentatiton where we report known errors in the annotations and potentially controversial choices we made in the loaders?

**Comment by keunwoochoi** [comment]
> until we decide otherwise, to respect the annotations as they are even if we know there are mistakes.

+1

**Comment by rabitt** [comment]
> Maybe we can create a place in the documentatiton where we report known errors in the annotations and potentially controversial choices we made in the loaders?

I opened #98 . For now closing this and we can eventually put this discussion there.
