### ISSUE TITLE
Jams and annotations consistency

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#85]
We should write a ‘to_jams’ function to convert data to the jams format, and make clear we don’t test annotations consistency but only that the loaders are doing their job. The ‘to_jams’ function would allow people to check themselves.

**Comment by tomxi** [comment]
+1 for the ‘to_jams’ function!!

Jams is easy for me to work with, visualize etc, and to prepare interval labels into dense time varying labels, it’s easily done with PUMPP.

 It will be nice to get this in to the api before the stable release.

I’d like to help on this one but need to think a bit about api design... feels like it should be a BaseClass function that’s inherited and slightly modified for each of the existing namedtuple annotation formats.

Thoughts?

**Comment by tomxi** [comment]
Tagging @rabitt

**Comment by rabitt** [comment]
Overall in the API we've tried to avoid having all of the mirdata Track objects inherit from a base class, since there's actually very little that's shared from one loader to another. That could of course change though! If we keep things as they currently are, I can imagine a utility function/module that takes different named tuples and converts them to jams, and each data loader's `.to_jams()` function would be custom, calling the utility function/s. What do you think @tomxi ?

**Comment by magdalenafuentes** [comment]
+1 on a `mirdata.utils.to_jams()` function that checks the annotation type and converts it to `jams` accordingly!

**Comment by tomxi** [comment]
This sounds like a great way to go

**Comment by magdalenafuentes** [comment]
@tomxi please take a look at #130 

I wrote some initial ideas on this, just to keep it rolling. For now just `beats` and `sections`, with the `multi_segment` data type for `salami`. Let me know what do you think!
